
default_config:
#
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


homeassistant:

  name: Tian Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Asia/Shanghai
  

# 启用配置界面
config:

frontend:
  themes: !include_dir_merge_named themes

# 自动发现一些设备
#discovery:

# 启用显示跟踪设备位置的地图
map:

# 跟踪太阳
sun:

# 激活iOS客户端
#ios:

# 开启homekit 支持
homekit:
  filter:
    include_domains:
      - light
      - fan
      - sensor
      - switch

# 设备

#fan:
#  - platform: xiaomi_miio
#    host: !secret airpurifierhost
#    token: !secret airpurifiertoken
#    name: airpurifier

#switch:
#  - platform: xiaomi_miio
#    host: !secret plug1host
#    token: !secret plug1token
#    name: plug1

yeelight:
  devices:
    !secret wsydhost:
      name: 主卧右灯
#    !secret ttmdhost:
#      name: 榻榻米灯

#sensor:
#  - platform: template
#    sensors:
#      airpurifier_temp:
#        friendly_name: 主卧温度
#        value_template: '{{ states.fan.airpurifier.attributes.temperature }}'
#        unit_of_measurement: 'C'
#      airpurifier_humi:
#        friendly_name: 主卧湿度
#        value_template: '{{ states.fan.airpurifier.attributes.humidity }}'
#        unit_of_measurement: '%'

#  - platform: time_date
#    display_options:
#      - 'time'
#      - 'date'
#      - 'date_time'

# 记录到数据库中，有 history 和 logbook 去处理
recorder:
  purge_interval: 3

# 记录事件，按照时间顺序显示房屋发生的所有变化
logbook:
  exclude:
    domains:
      - media_player
    entities:
      - sun.sun
      - sensor.date
      - sensor.time
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.load_1m


# 支持随着时间的推移跟踪状态变化
history:
  include:
    domains:
      - sensor
      - switch
      - light
      - binary_sensor

  exclude:
    entities:
      - sun.sun
      - sensor.date
      - sensor.time





